logging.level.com.worldremit.atms.clients.ATMClient: DEBUG

finder:
  maxUnderlyingClientRadiusInMiles: 10
  maxResults: 21

validation:
  maxRadiusInMiles: 31

client:
  url: https://api.hsbc.com/x-open-banking/v2.2
  uri: /atms/geo-location/lat/{lat}/long/{long}